version: '2'

networks:
    LEMP:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: php_nginx_containter-nginx
        ports:
            - "8090:80"
        volumes:
            - ./code:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP  

    php:
        build: ./
        container_name: php_nginx_containter
        volumes:
            - ./code:/code
            - ./conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - "9089:9000"       
        networks:
            - LEMP